#!/usr/bin/env node

const esbuild = require('esbuild');
const path = require('path');
const clc = require('cli-color');

const watch = process.argv.indexOf('--watch') >= 0;

const files = [
    'assets/js/form.js',
    'assets/js/custom-cart-postcode.js',
    'assets/js/custom-product-postcode.js',
    'assets/js/progress-bar.js',
    'assets/css/form.css',
    'assets/css/custom-postcode.css'
];

for (const file of files) {
    build(file);
}

async function build(entry) {
    const ext = path.extname(entry);
    const regex = new RegExp(ext + '$');
    esbuild
        .build({
            entryPoints: [entry],
            outfile: entry.replace(regex, '.min' + ext),
            bundle: true,
            minify: true,
        })
        .then((result) => {
            if (result.errors.length === 0) {
                console.log(clc.green(entry + ' OK!'));
            } else {
                console.log(entry + 'error: ' + result.errors[0]);
            }
        });
}
